name: Deploy to Dev

on:
  push:
    branches:
      - "develop"
      
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: pull and build
        env:
          DEV_HOST: ${{ secrets.DEV_HOST }}
          PASS: ${{ secrets.PASS }}
        run: |
          ssh -i /root/.ssh/id_rsa $DEV_HOST << EOF
          cd /root/audit-web/audit-web
          git checkout develop
          echo $PASS | git pull
          docker-compose up -d --build
          EOF
