name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: "#dev"

    steps:
    - uses: actions/checkout@v1
    
    - name: Deploy Docker
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ${{secrets.ADB_DEV_HOST}}
        ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
        ssh_public_key: ${{secrets.ADB_DEV_PUBLIC_KEY}}
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: /root/audit-web
        stack_file_name: docker-compose.yml
        args: up -d --build
